### ISSUE TITLE
Feature: Add a fact author column

### ISSUE THREAD

**Issue by Karandra** [Dakraid/SkybotV2#5]
# Description
From Neterve's words the DB stores following information:
- Nickname
- User#Number
- User ID
- ~~IP~~
- Internal ID

This is more a website feature request than for the bot itself, but anyway. I think it'll be useful to have a (searchable and filterable) column with the fact author. I'm not sure which field is better Nickname or User#Number. There could possibly be some issues with GDPR (as Thallassa reminded us) so I'm not sure how feasible this is.

**Comment by Dakraid** [comment]
No longer an issue as it has been changed a while ago.

**Comment by Karandra** [comment]
Mere mortals aren't going to ever see it.
